# Generated by Django 5.2.7 on 2025-11-11 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_cong_viec', models.CharField(max_length=255, verbose_name='Tên công việc')),
                ('don_vi_gui', models.CharField(max_length=100, verbose_name='Đơn vị gửi')),
                ('thoi_gian_tra', models.DateTimeField(verbose_name='Thời gian trả')),
                ('da_nhan', models.BooleanField(default=False, verbose_name='Đã nhận')),
                ('hoan_thanh', models.BooleanField(default=False, verbose_name='Hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian cập nhật')),
                ('nguoi_nhan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
            ],
            options={
                'verbose_name': 'Công việc',
                'verbose_name_plural': 'Quản lý Công việc',
                'ordering': ['thoi_gian_tra'],
            },
        ),
    ]
