# Generated by Django 5.0.6 on 2025-11-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ngay_hoan_thanh',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày giờ hoàn thành'),
        ),
        migrations.AddField(
            model_name='task',
            name='ngay_nhan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày giờ nhận'),
        ),
    ]
